collections_config:
  data:
    path: "data"
    label: "Profile and Settings"
  pages:
    path: "content/pages"
    output: true
    url: "/[slug]"
    _enabled_editors:
      - visual
      - content
  team:
    path: "content/team"
    output: true
    url: "team/[slug]"
    _enabled_editors:
      - visual
      - content
collection_groups:
  - heading: Profile and Settings
    collections:
      - data
  - heading: Pages
    collections:
      - pages
      - listings
      - team
      - legal
  - heading: Blog
    collections:
      - blog
paths:
  uploads: images
_inputs:
  body:
    type: markdown
  image:
    type: image
  logo:
    type: image
  favicon:
    type: image
  photo:
    type: image